# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_py',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some', models.CharField(max_length=10)),
            ],
        ),
    ]
